#!/bin/sh 

mode=$1

if [ "$mode" = "device" ]; then
	devmem 0x10000040 32 0x0b800096
	devmem 0x13500000 32 0x001100cc
	echo "Set to USB device ..."
	exit
elif [ "$mode" = "host" ]; then 
	devmem 0x10000040 32 0x0b000096
	echo "Set to USB host ..."
	exit
fi

echo "Usage: ingenic_usb <host/device>"
